spring:
  application:
    name: AIGNbatch
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  quartz:
#    job-store-type: memory # Quartz가 메모리를 사용하도록 설정
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          properties-file: classpath:quartz.properties

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.quartz: DEBUG

jobs:
  list:
    - name: SimpleQuartzJob
      jobClass: com.nhbank.batchquartz.job.SimpleQuartzJob
      schedule: "*/5 * * * * ?"
    - name: TestQuartzJob
      jobClass: com.nhbank.batchquartz.job.TestQuartzJob
      schedule: "*/10 * * * * ?"
#    - name: job1
#      jobClass: com.nhbank.batchquartz.job
#      schedule: "*/5 * * * * ?"